import test from "node:test";
import assert from "node:assert/strict";
import os from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";
import fs from "fs-extra";
import { getGitignore, mergeGitignoreContents, mergeGitignoreForImport, scaffoldGitignore } from "../src/system/gitignore.ts";

const templatesDir = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..", "src", "templates", "gitignore");

const COMMON_RULES = [/^node_modules\/$/m, /^\.env\.\*$/m, /^!\.env\.example$/m, /^\.DS_Store$/m, /^\.acli\/$/m, /^\*\.log$/m];

test("every project type gets its own rules plus the shared ones", async () => {
  const expected = {
    react: [/for a React \(Vite\) project/, /^dist\/$/m, /^coverage\/$/m],
    nextjs: [/for a Next\.js project/, /^\.next\/$/m, /^next-env\.d\.ts$/m],
    laravel: [/for a Laravel project/, /^\/backend\/vendor\/$/m, /^\.phpunit\.result\.cache$/m],
    wordpress: [/for a WordPress project/, /^\/wp-config\.php$/m, /^\/wp-content\/uploads\/$/m],
  };
  for (const [type, patterns] of Object.entries(expected)) {
    const content = await getGitignore(type);
    for (const pattern of [...patterns, ...COMMON_RULES]) assert.match(content, pattern, `${type}: ${pattern}`);
  }
});

test("shared rules appear once, not repeated by each type template", async () => {
  for (const type of ["react", "nextjs", "laravel", "wordpress"]) {
    const content = await getGitignore(type);
    assert.equal(content.match(/^\.acli\/$/gm)?.length, 1, type);
    assert.equal(content.match(/^node_modules\/?$/gm)?.length, 1, type);
  }
});

test("getGitignore resolves aliases (wp-existing and wp-* -> wordpress, next -> nextjs)", async () => {
  for (const alias of ["wp-existing", "wp-theme", "wp-woo", "wp-react"]) assert.equal(await getGitignore(alias), await getGitignore("wordpress"));
  assert.equal(await getGitignore("next"), await getGitignore("nextjs"));
});

test("an unknown project type gets only the shared rules", async () => {
  const content = await getGitignore("some-type-with-no-template");
  assert.match(content, /^# \.gitignore generated by A-CLI\.$/m);
  for (const pattern of COMMON_RULES) assert.match(content, pattern);
});

test("scaffoldGitignore writes the resolved template to <targetDir>/.gitignore", async () => {
  const directory = await fs.mkdtemp(path.join(os.tmpdir(), "acli-git-utils-"));
  await scaffoldGitignore(directory, "wordpress");
  const written = await fs.readFile(path.join(directory, ".gitignore"), "utf8");
  assert.equal(written, await getGitignore("wordpress"));
  await fs.remove(directory);
});

test("import replaces the one-line .acli placeholder with the complete WordPress template", async () => {
  const directory = await fs.mkdtemp(path.join(os.tmpdir(), "acli-git-utils-import-"));
  await fs.writeFile(path.join(directory, ".gitignore"), ".acli/\n");
  await mergeGitignoreForImport(directory, "wordpress");
  const written = await fs.readFile(path.join(directory, ".gitignore"), "utf8");
  assert.equal(written, await getGitignore("wordpress"));
  assert.match(written, /^\/wp-config\.php$/m);
  assert.match(written, /^\/wp-content\/uploads\/$/m);
  await fs.remove(directory);
});

test("import preserves a remote project .gitignore and appends only missing A-CLI template rules", async () => {
  const remote = "# Project-specific rules\n/custom-cache/\n/wp-admin/\n";
  const current = ".acli/\n";
  const template = await getGitignore("wordpress");
  const merged = mergeGitignoreContents(current, template, remote);

  assert.ok(merged.startsWith(remote.trimEnd()), "the tracked remote file must remain the authoritative base");
  assert.match(merged, /^\/custom-cache\/$/m);
  assert.match(merged, /^\.acli\/$/m);
  assert.match(merged, /^\/wp-config\.php$/m);
  assert.equal(merged.match(/^\/wp-admin\/$/gm)?.length, 1, "an existing remote rule must not be duplicated");
});
