import fs from "fs-extra";
import path from "path";
import { fileURLToPath } from "url";
import { runCommand } from "./commandRunner.ts";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const TEMPLATES_DIR = path.join(__dirname, "..", "templates", "gitignore");

// Which template adds the rules specific to a project type. Everything
// shared by all projects (dependencies, env files, logs, editors, OS files,
// .acli/) lives in common.gitignore.tpl.
const TYPE_TEMPLATES: Record<string, { template: string; label: string }> = {
  react: { template: "react", label: "React (Vite)" },
  nextjs: { template: "nextjs", label: "Next.js" },
  next: { template: "nextjs", label: "Next.js" },
  laravel: { template: "laravel", label: "Laravel" },
  wordpress: { template: "wordpress", label: "WordPress" },
  "wp-existing": { template: "wordpress", label: "WordPress" },
  "wp-theme": { template: "wordpress", label: "WordPress" },
  "wp-woo": { template: "wordpress", label: "WordPress" },
  "wp-react": { template: "wordpress", label: "WordPress" },
};

// Used only if common.gitignore.tpl itself can't be read.
const FALLBACK_COMMON = "node_modules/\n.env\n.env.*\n!.env.example\n*.log\n.DS_Store\n.acli/\n";

async function readTemplate(name: string): Promise<string | null> {
  try {
    return await fs.readFile(path.join(TEMPLATES_DIR, `${name}.gitignore.tpl`), "utf-8");
  } catch {
    // Missing or unreadable (e.g. not a file) — callers fall back.
    return null;
  }
}

/**
 * The .gitignore A-CLI writes for a project type: that type's own rules
 * (build output, framework folders) followed by the rules every project
 * shares. An unknown type gets the shared rules only.
 */
export async function getGitignore(type: string): Promise<string> {
  const known = TYPE_TEMPLATES[type];
  const specific = known ? await readTemplate(known.template) : null;
  const common = (await readTemplate("common")) ?? FALLBACK_COMMON;
  const header = `# .gitignore generated by A-CLI${specific ? ` for a ${known!.label} project` : ""}.`;
  return `${[header, specific?.trim(), common.trim()].filter(Boolean).join("\n\n")}\n`;
}

/** Writes a fresh .gitignore for a project type. */
export async function scaffoldGitignore(targetDir: string, type: string): Promise<void> {
  await fs.outputFile(path.join(targetDir, ".gitignore"), await getGitignore(type));
}

/**
 * Adds A-CLI's rules for a project type to a .gitignore another tool already
 * wrote (create-vite, create-next-app), keeping that file's own rules first
 * and appending only the ones it is missing.
 */
export async function applyGitignoreTemplate(targetDir: string, type: string): Promise<void> {
  const gitignorePath = path.join(targetDir, ".gitignore");
  const current = (await fs.pathExists(gitignorePath)) ? await fs.readFile(gitignorePath, "utf8") : "";
  await fs.outputFile(gitignorePath, mergeGitignoreContents(current, await getGitignore(type)));
}

/**
 * Builds an import-safe .gitignore. A fetched repository's tracked file is
 * authoritative and stays intact; local/import-generated rules and missing
 * template patterns are appended. If there is no remote baseline and the
 * only local rule is the `.acli/` entry created by writeLink(), the complete
 * project template is materialized instead of leaving that one-line file.
 */
export async function mergeGitignoreForImport(targetDir: string, type: string): Promise<void> {
  const gitignorePath = path.join(targetDir, ".gitignore");
  const current = await fs.pathExists(gitignorePath) ? await fs.readFile(gitignorePath, "utf8") : "";
  const template = await getGitignore(type);
  let baseline: string | null = null;

  if (await fs.pathExists(path.join(targetDir, ".git"))) {
    try {
      baseline = String(await runCommand("git", ["show", "HEAD:.gitignore"], { cwd: targetDir }));
    } catch { /* A new/empty remote or a repository without .gitignore. */ }
  }

  const merged = mergeGitignoreContents(current, template, baseline);
  await fs.writeFile(gitignorePath, merged);
}

export function mergeGitignoreContents(current: string, template: string, baseline: string | null = null): string {
  const currentRules = activeRules(current);

  if (!baseline?.trim() && (currentRules.size === 0 || (currentRules.size === 1 && currentRules.has(".acli/")))) {
    return ensureFinalNewline(template);
  }

  const primary = baseline?.trim() ? baseline : current;
  const known = activeRules(primary);
  const additions: string[] = [];
  for (const rule of [...currentRules, ...activeRules(template)]) {
    if (known.has(rule)) continue;
    known.add(rule);
    additions.push(rule);
  }
  if (!additions.length) return ensureFinalNewline(primary);
  return `${primary.trimEnd()}\n\n# A-CLI additions\n${additions.join("\n")}\n`;
}

function activeRules(content: string): Set<string> {
  return new Set(content.split(/\r?\n/).map((line) => line.trim()).filter((line) => line && !line.startsWith("#")));
}

function ensureFinalNewline(content: string): string {
  return `${content.trimEnd()}\n`;
}
