import BaseStrategy from "./BaseStrategy.js";
import fs from "fs-extra";
import path from "path";
import { scaffoldGitignore } from "../utils/git.js";

export default class NextjsStrategy extends BaseStrategy {
  async scaffold(targetDir, ctx) {
    if (!ctx.skipEnvironment) {
      await this.scaffoldEnvironment(targetDir, ctx);
    }

    const { projectName } = ctx;
    const srcDir = path.join(targetDir, "src");

    await fs.ensureDir(path.join(srcDir, "app"));
    await fs.ensureDir(path.join(srcDir, "components"));
    await fs.ensureDir(path.join(srcDir, "lib"));

    await fs.writeFile(
      path.join(srcDir, "app", "layout.tsx"),
      `import type { Metadata } from 'next';\nimport type { ReactNode } from 'react';\nimport './globals.css';\n\nexport const metadata: Metadata = {\n  title: '${projectName}',\n  description: 'Generated by project-setup',\n};\n\nexport default function RootLayout({ children }: Readonly<{ children: ReactNode }>) {\n  return (\n    <html lang="en">\n      <body>{children}</body>\n    </html>\n  );\n}\n`,
    );

    await fs.writeFile(
      path.join(srcDir, "app", "page.tsx"),
      `export default function Home() {\n  return (\n    <main className="page-shell">\n      <section>\n        <p>Next.js App Router</p>\n        <h1>${projectName}</h1>\n      </section>\n    </main>\n  );\n}\n`,
    );

    await fs.writeFile(
      path.join(srcDir, "app", "globals.css"),
      `:root {\n  color: #1b1f24;\n  background: #f6f7f9;\n  font-family: Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;\n}\n\nbody {\n  margin: 0;\n}\n\n.page-shell {\n  display: grid;\n  min-height: 100vh;\n  place-items: center;\n  padding: 2rem;\n}\n\nsection {\n  max-width: 44rem;\n}\n\np {\n  color: #0f766e;\n  font-weight: 700;\n  letter-spacing: 0;\n  text-transform: uppercase;\n}\n\nh1 {\n  font-size: clamp(2.5rem, 8vw, 5rem);\n  line-height: 1;\n}\n`,
    );

    const apiUrl = ctx.useLaravel
      ? "http://localhost:8000/api"
      : "https://api.example.com";
    await fs.writeFile(
      path.join(srcDir, "lib", "api.ts"),
      `export const API_URL = process.env.NEXT_PUBLIC_API_URL || "${apiUrl}";\n`,
    );

    await fs.writeFile(
      path.join(targetDir, "next.config.mjs"),
      `/** @type {import('next').NextConfig} */\nconst nextConfig = {};\nexport default nextConfig;\n`,
    );

    const nextPkg = {
      name: projectName,
      version: "0.1.0",
      type: "module",
      private: true,
      scripts: {
        dev: "next dev",
        build: "next build",
        lint: "next lint",
        format: "prettier --write .",
        start: "next start",
      },
      dependencies: {
        next: "latest",
        react: "latest",
        "react-dom": "latest",
      },
      devDependencies: {
        "@types/node": "latest",
        "@types/react": "latest",
        "@types/react-dom": "latest",
        eslint: "latest",
        "eslint-config-next": "latest",
        prettier: "^3.0.0",
        typescript: "latest",
      },
    };
    await fs.writeJSON(path.join(targetDir, "package.json"), nextPkg, {
      spaces: 2,
    });

    await fs.writeJSON(path.join(targetDir, "tsconfig.json"), {
      compilerOptions: {
        target: "ES2017",
        lib: ["dom", "dom.iterable", "esnext"],
        allowJs: true,
        skipLibCheck: true,
        strict: true,
        noEmit: true,
        esModuleInterop: true,
        module: "esnext",
        moduleResolution: "bundler",
        resolveJsonModule: true,
        isolatedModules: true,
        jsx: "preserve",
        incremental: true,
        plugins: [{ name: "next" }],
        paths: { "@/*": ["./src/*"] },
      },
      include: ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
      exclude: ["node_modules"],
    }, { spaces: 2 });
    await fs.writeFile(path.join(targetDir, "next-env.d.ts"), `/// <reference types="next" />\n/// <reference types="next/image-types/global" />\n`);
    await fs.writeFile(path.join(targetDir, ".prettierrc"), `{\n  "singleQuote": true,\n  "trailingComma": "all"\n}\n`);
    await fs.writeFile(path.join(targetDir, ".editorconfig"), `root = true\n\n[*]\ncharset = utf-8\nend_of_line = lf\ninsert_final_newline = true\nindent_style = space\nindent_size = 2\n`);
    await fs.writeFile(path.join(targetDir, ".env.example"), `NEXT_PUBLIC_API_URL=${apiUrl}\n`);
    await scaffoldGitignore(targetDir, "nextjs");
  }

  getTemplateType() {
    return "nextjs";
  }
}
